"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var modelController_1 = require("../controllers/modelController");
var modelRouter = (0, express_1.Router)();
modelRouter.post("/plans", modelController_1.createFinancialPlan);
modelRouter.get("/plans/:id", modelController_1.getSpecificFinancialPlan);
modelRouter.post("/webscrape", modelController_1.webscrape);
modelRouter.post("/rmdscrape", modelController_1.rmdWebscrape);
modelRouter.post("/plans/all", modelController_1.getAllFinancialPlans);
modelRouter.post("/investment-types", modelController_1.createInvestmentType);
modelRouter.post("/investment-types/find", modelController_1.findInvestmentType);
modelRouter.get("/investment-types/id/:id", modelController_1.getInvestmentTypeById);
modelRouter.get("/investment-types/all", modelController_1.getAllInvestmentTypes);
modelRouter.get("/:plan/EventSeries/all", modelController_1.getAllEvents);
modelRouter.put("/plans/:id", modelController_1.updateFinancialPlan);
modelRouter.get("/:planId/investments", modelController_1.getInvestmentsByPlanId);
modelRouter.delete("/investment-types/:id", modelController_1.deleteInvestmentTypeById);
modelRouter.get("/:planId/simulation-results", modelController_1.getInvestmentsByPlanId);
exports.default = modelRouter;
